AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template: Sample
  template showing how to create a VPC with two public subnets & two private subnets.
  Class A IP addresses are used for huge networks, like those deployed by Internet Service Providers (ISPs). Class A IP addresses support up to 16 million hosts (hosts are devices that connect to a network (computers, servers, switches, routers, printers…etc.) and a Class A network can be divided into 128 different networks. 
  Class B IP addresses are used for medium and large-sized networks in enterprises and organizations. They support up to 65,000 hosts on 16,000 individual networks. 
  Class C addresses are most common and used in small business and home networks. These support up to 256 hosts on each of 2 million networks. 
  Class C Private Range: 192.168.0.0 to 192.168.255.255
  The allowed block size is between a /16 netmask (65,536 IP addresses) and /28 netmask (16 IP addresses). 
Parameters:
  VpcCIDR:
    Type: String
    Default: "192.168.0.0/22"

  PublicSubnet1CIDR:
    Type: String
    Default: "192.168.0.0/24"

  PublicSubnet2CIDR:
    Type: String
    Default: "192.168.1.0/24"

  PrivateSubnet1CIDR:
    Type: String
    Default: "192.168.2.0/24"

  PrivateSubnet2CIDR:
    Type: String
    Default: "192.168.3.0/24"
Resources:
  VPC: 
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags: 
        - Key: Name
          Value: !Ref 'AWS::StackId'
  PublicSubnet1: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: !Ref VPC 
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags: 
        - Key: Name
          Value: !Ref 'AWS::StackId'
  PublicSubnet2: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: !Ref VPC 
      CidrBlock: !Ref PublicSubnet2CIDR
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags: 
        - Key: Name
          Value: !Ref 'AWS::StackId'
  PrivateSubnet1: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: !Ref VPC 
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags: 
        - Key: Name
          Value: !Ref 'AWS::StackId'
  PrivateSubnet2: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: !Ref VPC 
      CidrBlock: !Ref PrivateSubnet2CIDR
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags: 
        - Key: Name
          Value: !Ref 'AWS::StackId'
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable    
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  PrivateSubnet1ARouteTableAssociation: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnet2ARouteTableAssociation: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable    
